/**
 * aiDesignSuggestionsStore — S89-E2: AI Design Suggestions
 *
 * Manages AI suggestion panel state and suggestion list.
 * Suggestions are generated by useAISuggestions hook based on canvas content.
 */

import { create } from 'zustand';

export type SuggestionType = 'structure' | 'layout' | 'naming' | 'connection';

export interface AISuggestion {
  id: string;
  type: SuggestionType;
  icon: string;
  title: string;
  description: string;
  /** 'pending' | 'applied' | 'dismissed' */
  status: 'pending' | 'applied' | 'dismissed';
  /** Which chapter the suggestion applies to */
  targetChapter?: string;
  /** Card IDs involved in this suggestion */
  relatedCardIds?: string[];
}

interface AIDesignSuggestionsState {
  /** Whether the suggestions panel is open */
  isOpen: boolean;
  /** Toggle the panel open/closed */
  togglePanel: () => void;
  /** Open the panel */
  openPanel: () => void;
  /** Close the panel */
  closePanel: () => void;

  /** List of current suggestions */
  suggestions: AISuggestion[];
  /** Set the full suggestions list */
  setSuggestions: (suggestions: AISuggestion[]) => void;
  /** Mark a suggestion as applied */
  applySuggestion: (id: string) => void;
  /** Mark a suggestion as dismissed (user ignored it) */
  dismissSuggestion: (id: string) => void;
  /** Clear all suggestions */
  clearSuggestions: () => void;
}

export const useAIDesignSuggestionsStore = create<AIDesignSuggestionsState>((set) => ({
  isOpen: false,
  togglePanel: () => set((s) => ({ isOpen: !s.isOpen })),
  openPanel: () => set({ isOpen: true }),
  closePanel: () => set({ isOpen: false }),

  suggestions: [],
  setSuggestions: (suggestions) => set({ suggestions }),
  applySuggestion: (id) =>
    set((s) => ({
      suggestions: s.suggestions.map((sg) =>
        sg.id === id ? { ...sg, status: 'applied' } : sg
      ),
    })),
  dismissSuggestion: (id) =>
    set((s) => ({
      suggestions: s.suggestions.map((sg) =>
        sg.id === id ? { ...sg, status: 'dismissed' } : sg
      ),
    })),
  clearSuggestions: () => set({ suggestions: [] }),
}));
