/**
 * GET /api/canvas/export?projectId=xxx — Export prototype as downloadable archive
 *
 * Epic 6: S6.1 zip 导出
 * Output: .tar.gz archive containing Next.js project files
 */
import { NextRequest, NextResponse } from 'next/server';
import { createGzip } from 'zlib';
import { Readable } from 'stream';
import prisma from '@/lib/prisma';

export const dynamic = 'force-dynamic';

export async function GET(request: NextRequest) {
  try {
    const projectId = request.nextUrl.searchParams.get('projectId');

    if (!projectId) {
      return NextResponse.json({ error: 'Missing projectId query parameter' }, { status: 400 });
    }

    const canvasProject = await prisma.canvasProject.findUnique({
      where: { id: projectId },
      include: { pages: true },
    });

    if (!canvasProject) {
      return NextResponse.json({ error: 'Canvas project not found' }, { status: 404 });
    }

    const donePages = canvasProject.pages.filter((p) => p.status === 'done' && p.codeJson);
    if (donePages.length === 0) {
      return NextResponse.json(
        { error: 'No completed pages to export. Generate pages first.' },
        { status: 400 }
      );
    }

    // Build tar.gz stream using Node built-in modules
    const tarStream = buildTarStream(canvasProject.name, donePages);
    const gzip = createGzip();
    const stream = tarStream.pipe(gzip);

    const chunks: Buffer[] = [];
    for await (const chunk of stream) {
      chunks.push(Buffer.from(chunk));
    }

    const buffer = Buffer.concat(chunks);
    const safeName = canvasProject.name.replace(/[^a-zA-Z0-9-_]/g, '_').slice(0, 50);

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/gzip',
        'Content-Disposition': `attachment; filename="${safeName}-prototype.tar.gz"`,
        'Content-Length': String(buffer.length),
      },
    });
  } catch (error) {
    console.error('[canvas/export] Error:', error);
    return NextResponse.json({ error: 'Failed to export project' }, { status: 500 });
  }
}

interface DonePage {
  name: string;
  componentId: string;
  codeJson: string | null;
}

/**
 * Build a tar.gz stream from pages
 * Uses the PAX format tar (USTAR is simpler to generate manually)
 */
function buildTarStream(projectName: string, pages: DonePage[]): Readable {
  const entries: Array<{ path: string; content: string }> = [];

  // Root package.json
  entries.push({
    path: 'package.json',
    content: buildPackageJson(projectName),
  });

  // Root next.config.ts
  entries.push({
    path: 'next.config.ts',
    content: `/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;
`,
  });

  // Root tsconfig.json
  entries.push({
    path: 'tsconfig.json',
    content: JSON.stringify({
      compilerOptions: {
        target: 'ES2017',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./src/*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    }, null, 2),
  });

  // Root tailwind.config.ts
  entries.push({
    path: 'tailwind.config.ts',
    content: `import type { Config } from 'tailwindcss';
const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: { extend: {} },
  plugins: [],
};
export default config;
`,
  });

  // Root postcss.config.mjs
  entries.push({
    path: 'postcss.config.mjs',
    content: `export default {
  plugins: { tailwindcss: {}, autoprefixer: {} },
};
`,
  });

  // app/layout.tsx
  entries.push({
    path: 'src/app/layout.tsx',
    content: `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by VibeX Canvas',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN">
      <body className="antialiased">{children}</body>
    </html>
  );
}
`,
  });

  // app/globals.css
  entries.push({
    path: 'src/app/globals.css',
    content: `@tailwind base;
@tailwind components;
@tailwind utilities;
`,
  });

  // app/page.tsx (redirects to first page)
  entries.push({
    path: 'src/app/page.tsx',
    content: `import { redirect } from 'next/navigation';
export default function Home() {
  redirect('/${slugify(pages[0]?.name || 'page1')}');
}
`,
  });

  // Individual page files
  for (const page of pages) {
    const pageName = slugify(page.name);
    let code = '// No code generated';
    if (page.codeJson) {
      try {
        const parsed = JSON.parse(page.codeJson);
        code = parsed.code || '// No code available';
      } catch {
        code = page.codeJson;
      }
    }

    entries.push({
      path: `src/app/${pageName}/page.tsx`,
      content: code,
    });
  }

  // Convert entries to a tar-like stream
  // Using a simple concatenation approach with proper tar header format
  const buffers: Buffer[] = [];

  for (const entry of entries) {
    const header = makeTarHeader(entry.path, entry.content.length);
    buffers.push(header);
    buffers.push(Buffer.from(entry.content, 'utf-8'));
    // Pad to 512-byte block
    const totalBlockSize = Math.ceil(entry.content.length / 512) * 512;
    const padding = totalBlockSize - entry.content.length;
    if (padding > 0) {
      buffers.push(Buffer.alloc(padding));
    }
  }

  // End of archive: two empty 512-byte blocks
  buffers.push(Buffer.alloc(512));
  buffers.push(Buffer.alloc(512));

  return Readable.from(Buffer.concat(buffers));
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 30) || 'page';
}

function makeTarHeader(path: string, size: number): Buffer {
  const header = Buffer.alloc(512);
  const encoder = new TextEncoder();

  // File name (100 bytes)
  const nameBytes = encoder.encode(path.slice(0, 100));
  header.set(nameBytes, 0);

  // File mode (8 bytes, octal): 0644
  header.write('0000644', 100, 7, 'ascii');

  // Owner ID (8 bytes, octal): 0
  header.write('0000000', 108, 7, 'ascii');

  // Group ID (8 bytes, octal): 0
  header.write('0000000', 116, 7, 'ascii');

  // File size (12 bytes, octal)
  const sizeStr = size.toString(8).padStart(11, '0');
  header.write(sizeStr, 124, 11, 'ascii');

  // Modification time (12 bytes, octal): now
  const mtime = Math.floor(Date.now() / 1000).toString(8).padStart(11, '0');
  header.write(mtime, 136, 11, 'ascii');

  // Checksum (8 bytes): calculated after filling
  // Type flag (1 byte): regular file = '0'
  header.write('0', 156, 1, 'ascii');

  // Link name (100 bytes): empty
  // USTAR format indicator
  header.write('ustar', 257, 5, 'ascii');
  // USTAR version
  header.write('00', 263, 2, 'ascii');

  // Calculate checksum (bytes 0-355 and 384-511, treating checksum field as spaces)
  let sum = 0;
  for (let i = 0; i < 512; i++) {
    if (i >= 148 && i < 156) {
      sum += 32; // space character
    } else {
      sum += header[i];
    }
  }
  header.write(sum.toString(8).padStart(6, '0'), 148, 6, 'ascii');
  header.write(' ', 154, 1, 'ascii');

  return header;
}

function buildPackageJson(projectName: string): string {
  return JSON.stringify(
    {
      name: slugify(projectName) + '-prototype',
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint',
      },
      dependencies: {
        next: '^14.2.0',
        react: '^18.3.0',
        'react-dom': '^18.3.0',
      },
      devDependencies: {
        '@types/node': '^20.0.0',
        '@types/react': '^18.3.0',
        '@types/react-dom': '^18.3.0',
        autoprefixer: '^10.4.0',
        postcss: '^8.4.0',
        tailwindcss: '^3.4.0',
        typescript: '^5.4.0',
      },
    },
    null,
    2
  );
}
