/**
 * formatDDL.ts — Sprint5 T7: formatDDL + downloadDDL
 *
 * Formats DDLTable[] to SQL strings (MySQL / PostgreSQL).
 * Provides download trigger for .sql files.
 */

'use client';

import type { DDLTable } from './DDLGenerator';

export type DBType = 'mysql' | 'postgresql';

// ==================== T7: formatDDL ====================

/**
 * Format DDLTable[] as SQL DDL statement string.
 *
 * @param tables - DDLTable[] from generateDDL()
 * @param dbType - Target database dialect
 * @returns SQL DDL string
 *
 * @example
 * const sql = formatDDL(tables, 'mysql');
 * downloadDDL(tables, 'schema.sql');
 */
export function formatDDL(tables: DDLTable[], dbType: DBType = 'mysql'): string {
  if (tables.length === 0) {
    return '-- No tables to generate\n-- Add API endpoints to the API chapter to generate DDL';
  }

  const stmts: string[] = [];

  // Header
  stmts.push(`-- Generated by Vibex DDS Canvas`);
  stmts.push(`-- Database: ${dbType === 'mysql' ? 'MySQL 8.0' : 'PostgreSQL 14'}`);
  stmts.push(`-- Generated at: ${new Date().toISOString()}`);
  stmts.push('');
  stmts.push('SET NAMES utf8mb4;');
  stmts.push('SET FOREIGN_KEY_CHECKS = 0;');
  stmts.push('');

  for (const table of tables) {
    if (!table) continue;
    stmts.push(formatTable(table, dbType));
    stmts.push('');
  }

  stmts.push('SET FOREIGN_KEY_CHECKS = 1;');
  stmts.push('');

  return stmts.join('\n');
}

function formatTable(table: DDLTable, dbType: DBType): string {
  const lines: string[] = [];
  const quote = dbType === 'mysql' ? '`' : '"';

  if (table.comment) {
    lines.push(`-- Table: ${table.tableName}`);
    lines.push(`-- ${table.comment}`);
  } else {
    lines.push(`-- Table: ${table.tableName}`);
  }
  lines.push(`CREATE TABLE IF NOT EXISTS ${quote}${table.tableName}${quote} (`);

  const colLines: string[] = [];

  for (const col of table.columns) {
    const colDef = formatColumn(col, dbType);
    colLines.push(`  ${colDef}`);
  }

  // Primary key constraint
  const pkCols = table.columns.filter((c) => c.primaryKey);
  if (pkCols.length > 0) {
    colLines.push(
      `  PRIMARY KEY (${pkCols.map((c) => `${quote}${c.name}${quote}`).join(', ')})`
    );
  }

  lines.push(colLines.join(',\n'));
  lines.push(')');

  if (dbType === 'mysql') {
    lines.push('ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;');
  } else {
    lines.push(';');
  }

  return lines.join('\n');
}

function formatColumn(col: DDLColumn, dbType: DBType): string {
  const quote = dbType === 'mysql' ? '`' : '"';
  const parts = [`${quote}${col.name}${quote}`, col.type];

  if (!col.nullable) {
    parts.push('NOT NULL');
  } else {
    parts.push('NULL');
  }

  if (col.comment) {
    if (dbType === 'mysql') {
      parts.push(`COMMENT '${col.comment.replace(/'/g, "''")}'`);
    } else {
      parts.push(`COMMENT '${col.comment.replace(/'/g, "''")}'`);
    }
  }

  return parts.join(' ');
}

// ==================== downloadDDL ====================

/**
 * Trigger browser download of DDL SQL file.
 *
 * @param tables - DDLTable[] from generateDDL()
 * @param filename - Download filename (default: 'schema.sql')
 *
 * @example
 * downloadDDL(tables, 'ecommerce-schema.sql');
 */
export function downloadDDL(tables: DDLTable[], filename = 'schema.sql'): void {
  const sql = formatDDL(tables, 'mysql');
  const blob = new Blob([sql], { type: 'application/sql' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.sql') ? filename : `${filename}.sql`;
  a.click();
  URL.revokeObjectURL(url);
}
