/**
 * design-catalog.ts — 自动生成的设计风格目录
 *
 * 生成时间: 2026-04-13T19:40:51.130Z
 * 源数据: awesome-design-md-cn/data/designs.json
 */

export const DESIGN_CATALOG_VERSION = "1.0.0";

export const CATEGORIES = ['AI 产品', '内容与建站', '内容平台', '品牌官网', '开发工具', '效率协作', '精选风格', '自定义案例', '金融科技'] as const;
export type Category = typeof CATEGORIES[number];

export interface DesignEntry {
  slug: string;
  name: string;
  displayName: string;
  nameZh: string;
  category: Category;
  group: string;
  tagsZh: string[];
  styleKeywords: string[];
  descriptionZh: string;
  useCases: string[];
  previewLight?: string;
  previewDark?: string;
  readmePath?: string;
  designPath?: string;
  positioningZh?: string;
  bestFor?: string[];
  avoidFor?: string[];
  recommendedPromptZh?: string;
}

export const DESIGN_CATALOG: DesignEntry[] = [
  {
    slug: 'awesome-design-md-cn',
    name: 'awesome-design-md-cn',
    displayName: 'awesome-design-md-cn',
    nameZh: '本站风格',
    category: '自定义案例' as Category,
    group: 'custom',
    tagsZh: ['中文', '科技', '资源库', '筛选', '目录'],
    styleKeywords: ['冷灰科技风', '低疲劳浏览', '左侧筛选', '紧凑目录卡片'],
    descriptionZh: '',
    useCases: ['设计资源库', '导航目录页', '工具聚合页'],
    previewLight: 'design-md/awesome-design-md-cn/preview.html',
    previewDark: 'design-md/awesome-design-md-cn/preview-dark.html',
    designPath: 'design-md/awesome-design-md-cn/DESIGN.md',
    bestFor: ['设计资源库', '风格导航页', '文档索引页', '工具聚合页'],
    avoidFor: ['高情绪品牌大片页', '娱乐化活动落地页'],
    recommendedPromptZh: '参考 awesome-design-md-cn 的视觉语言，设计一个中文设计资源库或风格索引页：使用浅冷灰底与深色首屏，整体只保留少量冷蓝强调；左侧使用常驻筛选栏，右侧使用紧凑目录卡片；中文标题和正文保持克制，不堆大段文案，不使用高饱和彩色块，让页面在长时间浏览时仍然低疲劳、清晰且有科技感。',
  },
  {
    slug: 'airbnb',
    name: 'airbnb',
    displayName: 'Airbnb',
    nameZh: '爱彼迎',
    category: '品牌官网' as Category,
    group: 'reference',
    tagsZh: ['民宿', '旅行'],
    styleKeywords: ['民宿', '旅行', '温馨', '友好', '旅行感'],
    descriptionZh: '',
    useCases: ['品牌官网', '活动专题页', '服务介绍页'],
    previewLight: 'design-md/airbnb/preview.html',
    previewDark: 'design-md/airbnb/preview-dark.html',
    designPath: 'design-md/airbnb/DESIGN.md',
    bestFor: ['品牌官网', '活动专题页', '服务介绍页', '营销落地页'],
    avoidFor: ['复杂运维后台', '高密度列表管理页'],
    recommendedPromptZh: '参考 爱彼迎 / Airbnb 的视觉语言，设计一个中文 品牌官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'airtable',
    name: 'airtable',
    displayName: 'Airtable',
    nameZh: 'Airtable',
    category: '开发工具' as Category,
    group: 'reference',
    tagsZh: ['数据库', '效率'],
    styleKeywords: ['数据库', '效率', '灵活数据库', '电子表格', '模块化卡片式界面'],
    descriptionZh: '',
    useCases: ['开发者官网', '文档站', '控制台后台'],
    previewLight: 'design-md/airtable/preview.html',
    previewDark: 'design-md/airtable/preview-dark.html',
    designPath: 'design-md/airtable/DESIGN.md',
    bestFor: ['开发者官网', '文档站', '控制台后台'],
    avoidFor: ['强娱乐化内容页', '情绪导向的品牌叙事页'],
    recommendedPromptZh: '参考 Airtable / Airtable 的视觉语言，设计一个中文 开发者官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'apple',
    name: 'apple',
    displayName: 'Apple',
    nameZh: '苹果',
    category: '品牌官网' as Category,
    group: 'reference',
    tagsZh: ['科技', '高端'],
    styleKeywords: ['科技', '高端', '极致简洁', '大量留白', '高端科技感'],
    descriptionZh: '',
    useCases: ['品牌官网', '营销落地页', '企业介绍页'],
    previewLight: 'design-md/apple/preview.html',
    previewDark: 'design-md/apple/preview-dark.html',
    designPath: 'design-md/apple/DESIGN.md',
    bestFor: ['品牌官网', '营销落地页', '企业介绍页'],
    avoidFor: ['复杂运维后台', '高密度列表管理页'],
    recommendedPromptZh: '参考 苹果 / Apple 的视觉语言，设计一个中文 品牌官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'bmw',
    name: 'bmw',
    displayName: 'BMW',
    nameZh: '宝马',
    category: '品牌官网' as Category,
    group: 'reference',
    tagsZh: ['汽车', '豪华'],
    styleKeywords: ['汽车', '豪华', '德系豪华汽车官网', '精致光影与深邃质感'],
    descriptionZh: '',
    useCases: ['品牌官网', '营销落地页', '企业介绍页'],
    previewLight: 'design-md/bmw/preview.html',
    previewDark: 'design-md/bmw/preview-dark.html',
    designPath: 'design-md/bmw/DESIGN.md',
    bestFor: ['品牌官网', '营销落地页', '企业介绍页'],
    avoidFor: ['复杂运维后台', '高密度列表管理页'],
    recommendedPromptZh: '参考 宝马 / BMW 的视觉语言，设计一个中文 品牌官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'cal',
    name: 'cal',
    displayName: 'Cal',
    nameZh: 'Cal',
    category: '效率协作' as Category,
    group: 'reference',
    tagsZh: ['日历', '预约'],
    styleKeywords: ['日历', '预约', 'Calendly风格', '简洁预约排期界面'],
    descriptionZh: '',
    useCases: ['SaaS 后台', '工作台', '产品介绍页'],
    previewLight: 'design-md/cal/preview.html',
    previewDark: 'design-md/cal/preview-dark.html',
    designPath: 'design-md/cal/DESIGN.md',
    bestFor: ['SaaS 后台', '工作台', '产品介绍页', '工作台首页'],
    avoidFor: ['纯品牌大片式营销页', '重情绪化视觉实验页面'],
    recommendedPromptZh: '参考 Cal / Cal 的视觉语言，设计一个中文 SaaS 后台，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'claude',
    name: 'claude',
    displayName: 'Claude',
    nameZh: 'Claude',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '对话'],
    styleKeywords: ['AI', '对话', 'Anthropic旗下AI助手', '极简白底', '优雅紫'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/claude/preview.html',
    previewDark: 'design-md/claude/preview-dark.html',
    designPath: 'design-md/claude/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 Claude / Claude 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'clay',
    name: 'clay',
    displayName: 'Clay',
    nameZh: 'Clay',
    category: '精选风格' as Category,
    group: 'reference',
    tagsZh: ['CRM', '销售'],
    styleKeywords: ['CRM', '销售', '高端B2B销售CRM', '精致卡片与渐变'],
    descriptionZh: '',
    useCases: ['产品官网', '品牌页面', '界面参考'],
    previewLight: 'design-md/clay/preview.html',
    previewDark: 'design-md/clay/preview-dark.html',
    designPath: 'design-md/clay/DESIGN.md',
    bestFor: ['产品官网', '品牌页面', '界面参考'],
    avoidFor: ['对行业规范要求很强的系统'],
    recommendedPromptZh: '参考 Clay / Clay 的视觉语言，设计一个中文 产品官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'clickhouse',
    name: 'clickhouse',
    displayName: 'ClickHouse',
    nameZh: 'ClickHouse',
    category: '开发工具' as Category,
    group: 'reference',
    tagsZh: ['数据库', '技术'],
    styleKeywords: ['数据库', '技术', '数据库产品', '技术感深色界面'],
    descriptionZh: '',
    useCases: ['开发者官网', '文档站', '控制台后台'],
    previewLight: 'design-md/clickhouse/preview.html',
    previewDark: 'design-md/clickhouse/preview-dark.html',
    designPath: 'design-md/clickhouse/DESIGN.md',
    bestFor: ['开发者官网', '文档站', '控制台后台'],
    avoidFor: ['强娱乐化内容页', '情绪导向的品牌叙事页'],
    recommendedPromptZh: '参考 ClickHouse / ClickHouse 的视觉语言，设计一个中文 开发者官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'cohere',
    name: 'cohere',
    displayName: 'Cohere',
    nameZh: 'Cohere',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '技术'],
    styleKeywords: ['AI', '技术', 'AI初创公司', '现代科技感深蓝', '白色'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/cohere/preview.html',
    previewDark: 'design-md/cohere/preview-dark.html',
    designPath: 'design-md/cohere/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 Cohere / Cohere 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'coinbase',
    name: 'coinbase',
    displayName: 'Coinbase',
    nameZh: 'Coinbase',
    category: '金融科技' as Category,
    group: 'reference',
    tagsZh: ['金融', '加密'],
    styleKeywords: ['金融', '加密', '加密货币交易所', '专业金融深色界面'],
    descriptionZh: '',
    useCases: ['官网落地页', '支付产品页', '数据控制台'],
    previewLight: 'design-md/coinbase/preview.html',
    previewDark: 'design-md/coinbase/preview-dark.html',
    designPath: 'design-md/coinbase/DESIGN.md',
    bestFor: ['官网落地页', '支付产品页', '数据控制台', '定价页'],
    avoidFor: ['轻社交内容页', '卡通化活动页'],
    recommendedPromptZh: '参考 Coinbase / Coinbase 的视觉语言，设计一个中文 官网落地页，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'composio',
    name: 'composio',
    displayName: 'Composio',
    nameZh: 'Composio',
    category: '开发工具' as Category,
    group: 'reference',
    tagsZh: ['AI工具', '开发'],
    styleKeywords: ['AI工具', '开发', 'AI', 'Agent工具平台', '现代深色UI'],
    descriptionZh: '',
    useCases: ['开发者官网', '文档站', '控制台后台'],
    previewLight: 'design-md/composio/preview.html',
    previewDark: 'design-md/composio/preview-dark.html',
    designPath: 'design-md/composio/DESIGN.md',
    bestFor: ['开发者官网', '文档站', '控制台后台'],
    avoidFor: ['强娱乐化内容页', '情绪导向的品牌叙事页'],
    recommendedPromptZh: '参考 Composio / Composio 的视觉语言，设计一个中文 开发者官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'cursor',
    name: 'cursor',
    displayName: 'Cursor',
    nameZh: 'Cursor',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '开发'],
    styleKeywords: ['AI', '开发', 'AI代码编辑器官网', '深色沉浸式体验'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/cursor/preview.html',
    previewDark: 'design-md/cursor/preview-dark.html',
    designPath: 'design-md/cursor/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 Cursor / Cursor 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'elevenlabs',
    name: 'elevenlabs',
    displayName: 'ElevenLabs',
    nameZh: 'ElevenLabs',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '音频'],
    styleKeywords: ['AI', '音频', 'AI语音合成', '渐变深色', '科技感'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/elevenlabs/preview.html',
    previewDark: 'design-md/elevenlabs/preview-dark.html',
    designPath: 'design-md/elevenlabs/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 ElevenLabs / ElevenLabs 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'expo',
    name: 'expo',
    displayName: 'Expo',
    nameZh: 'Expo',
    category: '开发工具' as Category,
    group: 'reference',
    tagsZh: ['开发', '移动'],
    styleKeywords: ['开发', '移动', 'React', 'Native开发平台', '简洁技术文档风格'],
    descriptionZh: '',
    useCases: ['开发者官网', '文档站', '控制台后台'],
    previewLight: 'design-md/expo/preview.html',
    previewDark: 'design-md/expo/preview-dark.html',
    designPath: 'design-md/expo/DESIGN.md',
    bestFor: ['开发者官网', '文档站', '控制台后台'],
    avoidFor: ['强娱乐化内容页', '情绪导向的品牌叙事页'],
    recommendedPromptZh: '参考 Expo / Expo 的视觉语言，设计一个中文 开发者官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'ferrari',
    name: 'ferrari',
    displayName: 'Ferrari',
    nameZh: '法拉利',
    category: '品牌官网' as Category,
    group: 'reference',
    tagsZh: ['汽车', '豪华'],
    styleKeywords: ['汽车', '豪华', '意式超跑品牌官网', '黑白编辑感与极少量跃马红强调'],
    descriptionZh: '',
    useCases: ['品牌官网', '营销落地页', '企业介绍页'],
    previewLight: 'design-md/ferrari/preview.html',
    previewDark: 'design-md/ferrari/preview-dark.html',
    designPath: 'design-md/ferrari/DESIGN.md',
    bestFor: ['品牌官网', '营销落地页', '企业介绍页'],
    avoidFor: ['复杂运维后台', '高密度列表管理页'],
    recommendedPromptZh: '参考 法拉利 / Ferrari 的视觉语言，设计一个中文 品牌官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'figma',
    name: 'figma',
    displayName: 'Figma',
    nameZh: 'Figma',
    category: '效率协作' as Category,
    group: 'reference',
    tagsZh: ['设计', '协作'],
    styleKeywords: ['设计', '协作', '设计协作工具', '标志性的深色', '紫灰'],
    descriptionZh: '',
    useCases: ['SaaS 后台', '工作台', '产品介绍页'],
    previewLight: 'design-md/figma/preview.html',
    previewDark: 'design-md/figma/preview-dark.html',
    designPath: 'design-md/figma/DESIGN.md',
    bestFor: ['SaaS 后台', '工作台', '产品介绍页', '工作台首页'],
    avoidFor: ['纯品牌大片式营销页', '重情绪化视觉实验页面'],
    recommendedPromptZh: '参考 Figma / Figma 的视觉语言，设计一个中文 SaaS 后台，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'framer',
    name: 'framer',
    displayName: 'Framer',
    nameZh: 'Framer',
    category: '内容与建站' as Category,
    group: 'reference',
    tagsZh: ['建站', '无代码'],
    styleKeywords: ['建站', '无代码', '无代码建站工具', '艺术感深色着陆页'],
    descriptionZh: '',
    useCases: ['产品官网', '模板市场', '编辑器界面'],
    previewLight: 'design-md/framer/preview.html',
    previewDark: 'design-md/framer/preview-dark.html',
    designPath: 'design-md/framer/DESIGN.md',
    bestFor: ['产品官网', '模板市场', '编辑器界面', '建站工具官网'],
    avoidFor: ['金融级数据台', '过于严肃的企业门户'],
    recommendedPromptZh: '参考 Framer / Framer 的视觉语言，设计一个中文 产品官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'hashicorp',
    name: 'hashicorp',
    displayName: 'HashiCorp',
    nameZh: 'HashiCorp',
    category: '开发工具' as Category,
    group: 'reference',
    tagsZh: ['DevOps', '技术'],
    styleKeywords: ['DevOps', '技术', 'DevOps工具厂商', '蓝色技术文档风格'],
    descriptionZh: '',
    useCases: ['开发者官网', '文档站', '控制台后台'],
    previewLight: 'design-md/hashicorp/preview.html',
    previewDark: 'design-md/hashicorp/preview-dark.html',
    designPath: 'design-md/hashicorp/DESIGN.md',
    bestFor: ['开发者官网', '文档站', '控制台后台'],
    avoidFor: ['强娱乐化内容页', '情绪导向的品牌叙事页'],
    recommendedPromptZh: '参考 HashiCorp / HashiCorp 的视觉语言，设计一个中文 开发者官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'ibm',
    name: 'ibm',
    displayName: 'IBM',
    nameZh: 'IBM',
    category: '品牌官网' as Category,
    group: 'reference',
    tagsZh: ['企业', '科技'],
    styleKeywords: ['企业', '科技', '蓝色巨人企业风格', '国际化专业设计'],
    descriptionZh: '',
    useCases: ['品牌官网', '营销落地页', '企业介绍页'],
    previewLight: 'design-md/ibm/preview.html',
    previewDark: 'design-md/ibm/preview-dark.html',
    designPath: 'design-md/ibm/DESIGN.md',
    bestFor: ['品牌官网', '营销落地页', '企业介绍页'],
    avoidFor: ['复杂运维后台', '高密度列表管理页'],
    recommendedPromptZh: '参考 IBM / IBM 的视觉语言，设计一个中文 品牌官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'intercom',
    name: 'intercom',
    displayName: 'Intercom',
    nameZh: 'Intercom',
    category: '精选风格' as Category,
    group: 'reference',
    tagsZh: ['客服', '沟通'],
    styleKeywords: ['客服', '沟通', '客户沟通平台', '友好绿色品牌色'],
    descriptionZh: '',
    useCases: ['产品官网', '品牌页面', '界面参考'],
    previewLight: 'design-md/intercom/preview.html',
    previewDark: 'design-md/intercom/preview-dark.html',
    designPath: 'design-md/intercom/DESIGN.md',
    bestFor: ['产品官网', '品牌页面', '界面参考'],
    avoidFor: ['对行业规范要求很强的系统'],
    recommendedPromptZh: '参考 Intercom / Intercom 的视觉语言，设计一个中文 产品官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'kraken',
    name: 'kraken',
    displayName: 'Kraken',
    nameZh: 'Kraken',
    category: '金融科技' as Category,
    group: 'reference',
    tagsZh: ['加密', '金融'],
    styleKeywords: ['加密', '金融', '加密货币交易所', '海怪深色品牌'],
    descriptionZh: '',
    useCases: ['官网落地页', '支付产品页', '数据控制台'],
    previewLight: 'design-md/kraken/preview.html',
    previewDark: 'design-md/kraken/preview-dark.html',
    designPath: 'design-md/kraken/DESIGN.md',
    bestFor: ['官网落地页', '支付产品页', '数据控制台', '定价页'],
    avoidFor: ['轻社交内容页', '卡通化活动页'],
    recommendedPromptZh: '参考 Kraken / Kraken 的视觉语言，设计一个中文 官网落地页，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'lamborghini',
    name: 'lamborghini',
    displayName: 'Lamborghini',
    nameZh: '兰博基尼',
    category: '品牌官网' as Category,
    group: 'reference',
    tagsZh: ['汽车', '豪华'],
    styleKeywords: ['汽车', '豪华', '兰博基尼官网', '纯黑舞台感与金色强调的极致张力'],
    descriptionZh: '',
    useCases: ['品牌官网', '营销落地页', '企业介绍页'],
    previewLight: 'design-md/lamborghini/preview.html',
    previewDark: 'design-md/lamborghini/preview-dark.html',
    designPath: 'design-md/lamborghini/DESIGN.md',
    bestFor: ['品牌官网', '营销落地页', '企业介绍页'],
    avoidFor: ['复杂运维后台', '高密度列表管理页'],
    recommendedPromptZh: '参考 兰博基尼 / Lamborghini 的视觉语言，设计一个中文 品牌官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'linear.app',
    name: 'linear.app',
    displayName: 'Linear',
    nameZh: 'Linear',
    category: '效率协作' as Category,
    group: 'reference',
    tagsZh: ['项目管理', '极简'],
    styleKeywords: ['项目管理', '极简', '问题追踪神器', '深色极简工程美学'],
    descriptionZh: '',
    useCases: ['SaaS 后台', '工作台', '产品介绍页'],
    previewLight: 'design-md/linear.app/preview.html',
    previewDark: 'design-md/linear.app/preview-dark.html',
    designPath: 'design-md/linear.app/DESIGN.md',
    bestFor: ['SaaS 后台', '工作台', '产品介绍页', '工作台首页'],
    avoidFor: ['纯品牌大片式营销页', '重情绪化视觉实验页面'],
    recommendedPromptZh: '参考 Linear / Linear 的视觉语言，设计一个中文 SaaS 后台，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'lovable',
    name: 'lovable',
    displayName: 'Lovable',
    nameZh: 'Lovable',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['建站', 'AI'],
    styleKeywords: ['建站', 'AI', 'AI无代码建站', '温暖现代感'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/lovable/preview.html',
    previewDark: 'design-md/lovable/preview-dark.html',
    designPath: 'design-md/lovable/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 Lovable / Lovable 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'minimax',
    name: 'minimax',
    displayName: 'MiniMax',
    nameZh: 'MiniMax',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '大模型'],
    styleKeywords: ['AI', '大模型', 'AI大模型公司', '现代科技风格'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/minimax/preview.html',
    previewDark: 'design-md/minimax/preview-dark.html',
    designPath: 'design-md/minimax/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 MiniMax / MiniMax 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'mintlify',
    name: 'mintlify',
    displayName: 'Mintlify',
    nameZh: 'Mintlify',
    category: '开发工具' as Category,
    group: 'reference',
    tagsZh: ['文档', '开发'],
    styleKeywords: ['文档', '开发', '文档站点生成器', '简洁现代文档'],
    descriptionZh: '',
    useCases: ['开发者官网', '文档站', '控制台后台'],
    previewLight: 'design-md/mintlify/preview.html',
    previewDark: 'design-md/mintlify/preview-dark.html',
    designPath: 'design-md/mintlify/DESIGN.md',
    bestFor: ['开发者官网', '文档站', '控制台后台'],
    avoidFor: ['强娱乐化内容页', '情绪导向的品牌叙事页'],
    recommendedPromptZh: '参考 Mintlify / Mintlify 的视觉语言，设计一个中文 开发者官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'miro',
    name: 'miro',
    displayName: 'Miro',
    nameZh: 'Miro',
    category: '效率协作' as Category,
    group: 'reference',
    tagsZh: ['协作', '白板'],
    styleKeywords: ['协作', '白板', '在线白板协作', '创意工作空间'],
    descriptionZh: '',
    useCases: ['SaaS 后台', '工作台', '产品介绍页'],
    previewLight: 'design-md/miro/preview.html',
    previewDark: 'design-md/miro/preview-dark.html',
    designPath: 'design-md/miro/DESIGN.md',
    bestFor: ['SaaS 后台', '工作台', '产品介绍页', '工作台首页'],
    avoidFor: ['纯品牌大片式营销页', '重情绪化视觉实验页面'],
    recommendedPromptZh: '参考 Miro / Miro 的视觉语言，设计一个中文 SaaS 后台，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'mistral.ai',
    name: 'mistral.ai',
    displayName: 'Mistral AI',
    nameZh: 'Mistral',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '国际'],
    styleKeywords: ['AI', '国际', '法国AI实验室', '极简法式优雅'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/mistral.ai/preview.html',
    previewDark: 'design-md/mistral.ai/preview-dark.html',
    designPath: 'design-md/mistral.ai/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 Mistral / Mistral AI 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'mongodb',
    name: 'mongodb',
    displayName: 'MongoDB',
    nameZh: 'MongoDB',
    category: '开发工具' as Category,
    group: 'reference',
    tagsZh: ['数据库', 'NoSQL'],
    styleKeywords: ['数据库', 'NoSQL', '文档数据库', '绿色技术品牌'],
    descriptionZh: '',
    useCases: ['开发者官网', '文档站', '控制台后台'],
    previewLight: 'design-md/mongodb/preview.html',
    previewDark: 'design-md/mongodb/preview-dark.html',
    designPath: 'design-md/mongodb/DESIGN.md',
    bestFor: ['开发者官网', '文档站', '控制台后台'],
    avoidFor: ['强娱乐化内容页', '情绪导向的品牌叙事页'],
    recommendedPromptZh: '参考 MongoDB / MongoDB 的视觉语言，设计一个中文 开发者官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'notion',
    name: 'notion',
    displayName: 'Notion',
    nameZh: 'Notion',
    category: '效率协作' as Category,
    group: 'reference',
    tagsZh: ['笔记', '协作'],
    styleKeywords: ['笔记', '协作', '笔记与协作工具', '温暖纸张质感极简'],
    descriptionZh: '',
    useCases: ['SaaS 后台', '工作台', '产品介绍页'],
    previewLight: 'design-md/notion/preview.html',
    previewDark: 'design-md/notion/preview-dark.html',
    designPath: 'design-md/notion/DESIGN.md',
    bestFor: ['SaaS 后台', '工作台', '产品介绍页', '工作台首页'],
    avoidFor: ['纯品牌大片式营销页', '重情绪化视觉实验页面'],
    recommendedPromptZh: '参考 Notion / Notion 的视觉语言，设计一个中文 SaaS 后台，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'nvidia',
    name: 'nvidia',
    displayName: 'NVIDIA',
    nameZh: '英伟达',
    category: '品牌官网' as Category,
    group: 'reference',
    tagsZh: ['芯片', '科技'],
    styleKeywords: ['芯片', '科技', 'GPU芯片巨头', '深绿科技黑', '光效'],
    descriptionZh: '',
    useCases: ['品牌官网', '营销落地页', '企业介绍页'],
    previewLight: 'design-md/nvidia/preview.html',
    previewDark: 'design-md/nvidia/preview-dark.html',
    designPath: 'design-md/nvidia/DESIGN.md',
    bestFor: ['品牌官网', '营销落地页', '企业介绍页'],
    avoidFor: ['复杂运维后台', '高密度列表管理页'],
    recommendedPromptZh: '参考 英伟达 / NVIDIA 的视觉语言，设计一个中文 品牌官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'ollama',
    name: 'ollama',
    displayName: 'Ollama',
    nameZh: 'Ollama',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '本地'],
    styleKeywords: ['AI', '本地', '本地AI模型运行', '简约开发者工具'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/ollama/preview.html',
    previewDark: 'design-md/ollama/preview-dark.html',
    designPath: 'design-md/ollama/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 Ollama / Ollama 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'opencode.ai',
    name: 'opencode.ai',
    displayName: 'OpenCode',
    nameZh: 'OpenCode',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '代码'],
    styleKeywords: ['AI', '代码', 'AI代码平台', '现代开发者UI'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/opencode.ai/preview.html',
    previewDark: 'design-md/opencode.ai/preview-dark.html',
    designPath: 'design-md/opencode.ai/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 OpenCode / OpenCode 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'pinterest',
    name: 'pinterest',
    displayName: 'Pinterest',
    nameZh: 'Pinterest',
    category: '内容平台' as Category,
    group: 'reference',
    tagsZh: ['社交', '图片'],
    styleKeywords: ['社交', '图片', '图片社交平台', '明亮活泼红白'],
    descriptionZh: '',
    useCases: ['内容社区', '推荐流页面', '活动专题页'],
    previewLight: 'design-md/pinterest/preview.html',
    previewDark: 'design-md/pinterest/preview-dark.html',
    designPath: 'design-md/pinterest/DESIGN.md',
    bestFor: ['内容社区', '推荐流页面', '活动专题页'],
    avoidFor: ['表单密集型后台', '高度理性的文档站'],
    recommendedPromptZh: '参考 Pinterest / Pinterest 的视觉语言，设计一个中文 内容社区，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'posthog',
    name: 'posthog',
    displayName: 'PostHog',
    nameZh: 'PostHog',
    category: '精选风格' as Category,
    group: 'reference',
    tagsZh: ['分析', '产品'],
    styleKeywords: ['分析', '产品', '产品分析平台', '温暖黄色品牌'],
    descriptionZh: '',
    useCases: ['产品官网', '品牌页面', '界面参考'],
    previewLight: 'design-md/posthog/preview.html',
    previewDark: 'design-md/posthog/preview-dark.html',
    designPath: 'design-md/posthog/DESIGN.md',
    bestFor: ['产品官网', '品牌页面', '界面参考'],
    avoidFor: ['对行业规范要求很强的系统'],
    recommendedPromptZh: '参考 PostHog / PostHog 的视觉语言，设计一个中文 产品官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'raycast',
    name: 'raycast',
    displayName: 'Raycast',
    nameZh: 'Raycast',
    category: '效率协作' as Category,
    group: 'reference',
    tagsZh: ['效率', '工具'],
    styleKeywords: ['效率', '工具', 'macOS效率工具', '简约深色工具感'],
    descriptionZh: '',
    useCases: ['SaaS 后台', '工作台', '产品介绍页'],
    previewLight: 'design-md/raycast/preview.html',
    previewDark: 'design-md/raycast/preview-dark.html',
    designPath: 'design-md/raycast/DESIGN.md',
    bestFor: ['SaaS 后台', '工作台', '产品介绍页', '工作台首页'],
    avoidFor: ['纯品牌大片式营销页', '重情绪化视觉实验页面'],
    recommendedPromptZh: '参考 Raycast / Raycast 的视觉语言，设计一个中文 SaaS 后台，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'renault',
    name: 'renault',
    displayName: 'Renault',
    nameZh: '雷诺',
    category: '品牌官网' as Category,
    group: 'reference',
    tagsZh: ['汽车', '品牌'],
    styleKeywords: ['汽车', '品牌', '雷诺官网', '极具能量的渐变车展氛围与法式几何秩序'],
    descriptionZh: '',
    useCases: ['品牌官网', '营销落地页', '企业介绍页'],
    previewLight: 'design-md/renault/preview.html',
    previewDark: 'design-md/renault/preview-dark.html',
    designPath: 'design-md/renault/DESIGN.md',
    bestFor: ['品牌官网', '营销落地页', '企业介绍页'],
    avoidFor: ['复杂运维后台', '高密度列表管理页'],
    recommendedPromptZh: '参考 雷诺 / Renault 的视觉语言，设计一个中文 品牌官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'replicate',
    name: 'replicate',
    displayName: 'Replicate',
    nameZh: 'Replicate',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '云'],
    styleKeywords: ['AI', '云', 'AI模型云托管', '简洁开发者平台'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/replicate/preview.html',
    previewDark: 'design-md/replicate/preview-dark.html',
    designPath: 'design-md/replicate/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 Replicate / Replicate 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'resend',
    name: 'resend',
    displayName: 'Resend',
    nameZh: 'Resend',
    category: '开发工具' as Category,
    group: 'reference',
    tagsZh: ['邮件', 'API'],
    styleKeywords: ['邮件', 'API', '邮件API服务', '极简开发者邮件工具'],
    descriptionZh: '',
    useCases: ['开发者官网', '文档站', '控制台后台'],
    previewLight: 'design-md/resend/preview.html',
    previewDark: 'design-md/resend/preview-dark.html',
    designPath: 'design-md/resend/DESIGN.md',
    bestFor: ['开发者官网', '文档站', '控制台后台'],
    avoidFor: ['强娱乐化内容页', '情绪导向的品牌叙事页'],
    recommendedPromptZh: '参考 Resend / Resend 的视觉语言，设计一个中文 开发者官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'revolut',
    name: 'revolut',
    displayName: 'Revolut',
    nameZh: 'Revolut',
    category: '金融科技' as Category,
    group: 'reference',
    tagsZh: ['金融', '银行'],
    styleKeywords: ['金融', '银行', '数字银行', '现代金融科技感'],
    descriptionZh: '',
    useCases: ['官网落地页', '支付产品页', '数据控制台'],
    previewLight: 'design-md/revolut/preview.html',
    previewDark: 'design-md/revolut/preview-dark.html',
    designPath: 'design-md/revolut/DESIGN.md',
    bestFor: ['官网落地页', '支付产品页', '数据控制台', '定价页'],
    avoidFor: ['轻社交内容页', '卡通化活动页'],
    recommendedPromptZh: '参考 Revolut / Revolut 的视觉语言，设计一个中文 官网落地页，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'runwayml',
    name: 'runwayml',
    displayName: 'Runway',
    nameZh: 'Runway',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '视频'],
    styleKeywords: ['AI', '视频', 'AI视频生成', '前沿创意技术'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/runwayml/preview.html',
    previewDark: 'design-md/runwayml/preview-dark.html',
    designPath: 'design-md/runwayml/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 Runway / Runway 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'sanity',
    name: 'sanity',
    displayName: 'Sanity',
    nameZh: 'Sanity',
    category: '内容与建站' as Category,
    group: 'reference',
    tagsZh: ['CMS', '内容'],
    styleKeywords: ['CMS', '内容', '无头CMS平台', '内容优先设计'],
    descriptionZh: '',
    useCases: ['产品官网', '模板市场', '编辑器界面'],
    previewLight: 'design-md/sanity/preview.html',
    previewDark: 'design-md/sanity/preview-dark.html',
    designPath: 'design-md/sanity/DESIGN.md',
    bestFor: ['产品官网', '模板市场', '编辑器界面', '建站工具官网'],
    avoidFor: ['金融级数据台', '过于严肃的企业门户'],
    recommendedPromptZh: '参考 Sanity / Sanity 的视觉语言，设计一个中文 产品官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'sentry',
    name: 'sentry',
    displayName: 'Sentry',
    nameZh: 'Sentry',
    category: '开发工具' as Category,
    group: 'reference',
    tagsZh: ['开发', '监控'],
    styleKeywords: ['开发', '监控', '错误追踪平台', '开发者工具深色'],
    descriptionZh: '',
    useCases: ['开发者官网', '文档站', '控制台后台'],
    previewLight: 'design-md/sentry/preview.html',
    previewDark: 'design-md/sentry/preview-dark.html',
    designPath: 'design-md/sentry/DESIGN.md',
    bestFor: ['开发者官网', '文档站', '控制台后台'],
    avoidFor: ['强娱乐化内容页', '情绪导向的品牌叙事页'],
    recommendedPromptZh: '参考 Sentry / Sentry 的视觉语言，设计一个中文 开发者官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'spacex',
    name: 'spacex',
    displayName: 'SpaceX',
    nameZh: 'SpaceX',
    category: '品牌官网' as Category,
    group: 'reference',
    tagsZh: ['航天', '探索'],
    styleKeywords: ['航天', '探索', 'SpaceX官网', '太空探索深色沉浸'],
    descriptionZh: '',
    useCases: ['品牌官网', '营销落地页', '企业介绍页'],
    previewLight: 'design-md/spacex/preview.html',
    previewDark: 'design-md/spacex/preview-dark.html',
    designPath: 'design-md/spacex/DESIGN.md',
    bestFor: ['品牌官网', '营销落地页', '企业介绍页'],
    avoidFor: ['复杂运维后台', '高密度列表管理页'],
    recommendedPromptZh: '参考 SpaceX / SpaceX 的视觉语言，设计一个中文 品牌官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'spotify',
    name: 'spotify',
    displayName: 'Spotify',
    nameZh: 'Spotify',
    category: '内容平台' as Category,
    group: 'reference',
    tagsZh: ['音乐', '流媒体'],
    styleKeywords: ['音乐', '流媒体', '音乐流媒体', '绿色品牌深色模式'],
    descriptionZh: '',
    useCases: ['内容社区', '推荐流页面', '活动专题页'],
    previewLight: 'design-md/spotify/preview.html',
    previewDark: 'design-md/spotify/preview-dark.html',
    designPath: 'design-md/spotify/DESIGN.md',
    bestFor: ['内容社区', '推荐流页面', '活动专题页'],
    avoidFor: ['表单密集型后台', '高度理性的文档站'],
    recommendedPromptZh: '参考 Spotify / Spotify 的视觉语言，设计一个中文 内容社区，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'stripe',
    name: 'stripe',
    displayName: 'Stripe',
    nameZh: 'Stripe',
    category: '金融科技' as Category,
    group: 'reference',
    tagsZh: ['支付', '金融'],
    styleKeywords: ['支付', '金融', '支付API平台', '极致精致开发者文档'],
    descriptionZh: '',
    useCases: ['官网落地页', '支付产品页', '数据控制台'],
    previewLight: 'design-md/stripe/preview.html',
    previewDark: 'design-md/stripe/preview-dark.html',
    designPath: 'design-md/stripe/DESIGN.md',
    bestFor: ['官网落地页', '支付产品页', '数据控制台', '定价页'],
    avoidFor: ['轻社交内容页', '卡通化活动页'],
    recommendedPromptZh: '参考 Stripe / Stripe 的视觉语言，设计一个中文 官网落地页，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'supabase',
    name: 'supabase',
    displayName: 'Supabase',
    nameZh: 'Supabase',
    category: '开发工具' as Category,
    group: 'reference',
    tagsZh: ['后端', '开源'],
    styleKeywords: ['后端', '开源', '开源Firebase替代', '渐变深色技术'],
    descriptionZh: '',
    useCases: ['开发者官网', '文档站', '控制台后台'],
    previewLight: 'design-md/supabase/preview.html',
    previewDark: 'design-md/supabase/preview-dark.html',
    designPath: 'design-md/supabase/DESIGN.md',
    bestFor: ['开发者官网', '文档站', '控制台后台'],
    avoidFor: ['强娱乐化内容页', '情绪导向的品牌叙事页'],
    recommendedPromptZh: '参考 Supabase / Supabase 的视觉语言，设计一个中文 开发者官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'superhuman',
    name: 'superhuman',
    displayName: 'Superhuman',
    nameZh: 'Superhuman',
    category: '精选风格' as Category,
    group: 'reference',
    tagsZh: ['邮件', '高端'],
    styleKeywords: ['邮件', '高端', '极速邮件客户端', '奢华高端定位'],
    descriptionZh: '',
    useCases: ['产品官网', '品牌页面', '界面参考'],
    previewLight: 'design-md/superhuman/preview.html',
    previewDark: 'design-md/superhuman/preview-dark.html',
    designPath: 'design-md/superhuman/DESIGN.md',
    bestFor: ['产品官网', '品牌页面', '界面参考'],
    avoidFor: ['对行业规范要求很强的系统'],
    recommendedPromptZh: '参考 Superhuman / Superhuman 的视觉语言，设计一个中文 产品官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'tesla',
    name: 'tesla',
    displayName: 'Tesla',
    nameZh: '特斯拉',
    category: '品牌官网' as Category,
    group: 'reference',
    tagsZh: ['汽车', '科技'],
    styleKeywords: ['汽车', '科技', '特斯拉官网', '极简摄影驱动的科技产品展示气质'],
    descriptionZh: '',
    useCases: ['品牌官网', '营销落地页', '企业介绍页'],
    previewLight: 'design-md/tesla/preview.html',
    previewDark: 'design-md/tesla/preview-dark.html',
    designPath: 'design-md/tesla/DESIGN.md',
    bestFor: ['品牌官网', '营销落地页', '企业介绍页'],
    avoidFor: ['复杂运维后台', '高密度列表管理页'],
    recommendedPromptZh: '参考 特斯拉 / Tesla 的视觉语言，设计一个中文 品牌官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'together.ai',
    name: 'together.ai',
    displayName: 'Together AI',
    nameZh: 'Together AI',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '云'],
    styleKeywords: ['AI', '云', 'AI云平台', '渐变深色开发者UI'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/together.ai/preview.html',
    previewDark: 'design-md/together.ai/preview-dark.html',
    designPath: 'design-md/together.ai/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 Together AI / Together AI 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'uber',
    name: 'uber',
    displayName: 'Uber',
    nameZh: 'Uber',
    category: '品牌官网' as Category,
    group: 'reference',
    tagsZh: ['出行', '企业'],
    styleKeywords: ['出行', '企业', '出行巨头', '精致黑白企业风格'],
    descriptionZh: '',
    useCases: ['品牌官网', '营销落地页', '企业介绍页'],
    previewLight: 'design-md/uber/preview.html',
    previewDark: 'design-md/uber/preview-dark.html',
    designPath: 'design-md/uber/DESIGN.md',
    bestFor: ['品牌官网', '营销落地页', '企业介绍页'],
    avoidFor: ['复杂运维后台', '高密度列表管理页'],
    recommendedPromptZh: '参考 Uber / Uber 的视觉语言，设计一个中文 品牌官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'vercel',
    name: 'vercel',
    displayName: 'Vercel',
    nameZh: 'Vercel',
    category: '开发工具' as Category,
    group: 'reference',
    tagsZh: ['部署', '前端'],
    styleKeywords: ['部署', '前端', '前端部署平台', '极简深色开发者美学'],
    descriptionZh: '',
    useCases: ['开发者官网', '文档站', '控制台后台'],
    previewLight: 'design-md/vercel/preview.html',
    previewDark: 'design-md/vercel/preview-dark.html',
    designPath: 'design-md/vercel/DESIGN.md',
    bestFor: ['开发者官网', '文档站', '控制台后台'],
    avoidFor: ['强娱乐化内容页', '情绪导向的品牌叙事页'],
    recommendedPromptZh: '参考 Vercel / Vercel 的视觉语言，设计一个中文 开发者官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'voltagent',
    name: 'voltagent',
    displayName: 'VoltAgent',
    nameZh: 'VoltAgent',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', 'Agent'],
    styleKeywords: ['AI', 'Agent', 'VoltAgent自家官网', '极简技术感'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/voltagent/preview.html',
    previewDark: 'design-md/voltagent/preview-dark.html',
    designPath: 'design-md/voltagent/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 VoltAgent / VoltAgent 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'warp',
    name: 'warp',
    displayName: 'Warp',
    nameZh: 'Warp',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['终端', 'AI'],
    styleKeywords: ['终端', 'AI', 'AI终端应用', '现代终端美学'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/warp/preview.html',
    previewDark: 'design-md/warp/preview-dark.html',
    designPath: 'design-md/warp/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 Warp / Warp 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'webflow',
    name: 'webflow',
    displayName: 'Webflow',
    nameZh: 'Webflow',
    category: '内容与建站' as Category,
    group: 'reference',
    tagsZh: ['建站', '无代码'],
    styleKeywords: ['建站', '无代码', '无代码建站', '清晰蓝色教学风格'],
    descriptionZh: '',
    useCases: ['产品官网', '模板市场', '编辑器界面'],
    previewLight: 'design-md/webflow/preview.html',
    previewDark: 'design-md/webflow/preview-dark.html',
    designPath: 'design-md/webflow/DESIGN.md',
    bestFor: ['产品官网', '模板市场', '编辑器界面', '建站工具官网'],
    avoidFor: ['金融级数据台', '过于严肃的企业门户'],
    recommendedPromptZh: '参考 Webflow / Webflow 的视觉语言，设计一个中文 产品官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'wise',
    name: 'wise',
    displayName: 'Wise',
    nameZh: 'Wise',
    category: '金融科技' as Category,
    group: 'reference',
    tagsZh: ['金融', '汇款'],
    styleKeywords: ['金融', '汇款', '国际汇款平台', '简洁透明金融UI'],
    descriptionZh: '',
    useCases: ['官网落地页', '支付产品页', '数据控制台'],
    previewLight: 'design-md/wise/preview.html',
    previewDark: 'design-md/wise/preview-dark.html',
    designPath: 'design-md/wise/DESIGN.md',
    bestFor: ['官网落地页', '支付产品页', '数据控制台', '定价页'],
    avoidFor: ['轻社交内容页', '卡通化活动页'],
    recommendedPromptZh: '参考 Wise / Wise 的视觉语言，设计一个中文 官网落地页，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'x.ai',
    name: 'x.ai',
    displayName: 'xAI',
    nameZh: 'xAI',
    category: 'AI 产品' as Category,
    group: 'reference',
    tagsZh: ['AI', '日程'],
    styleKeywords: ['AI', '日程', 'AI日程助手', '简洁任务管理'],
    descriptionZh: '',
    useCases: ['AI 工具官网', '模型平台', '功能介绍页'],
    previewLight: 'design-md/x.ai/preview.html',
    previewDark: 'design-md/x.ai/preview-dark.html',
    designPath: 'design-md/x.ai/DESIGN.md',
    bestFor: ['AI 工具官网', '模型平台', '功能介绍页', '模型能力介绍'],
    avoidFor: ['强表格化后台', '政企风审批系统'],
    recommendedPromptZh: '参考 xAI / xAI 的视觉语言，设计一个中文 AI 工具官网，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
  {
    slug: 'zapier',
    name: 'zapier',
    displayName: 'Zapier',
    nameZh: 'Zapier',
    category: '效率协作' as Category,
    group: 'reference',
    tagsZh: ['自动化', '效率'],
    styleKeywords: ['自动化', '效率', '自动化平台', '经典蓝白效率工具'],
    descriptionZh: '',
    useCases: ['SaaS 后台', '工作台', '产品介绍页'],
    previewLight: 'design-md/zapier/preview.html',
    previewDark: 'design-md/zapier/preview-dark.html',
    designPath: 'design-md/zapier/DESIGN.md',
    bestFor: ['SaaS 后台', '工作台', '产品介绍页', '工作台首页'],
    avoidFor: ['纯品牌大片式营销页', '重情绪化视觉实验页面'],
    recommendedPromptZh: '参考 Zapier / Zapier 的视觉语言，设计一个中文 SaaS 后台，保留其配色、字重层级、卡片样式和留白节奏，同时把标题长度、正文排版和信息密度调整为适合中文阅读的形式。',
  },
] as const;