#!/usr/bin/env python3
"""
Parse Playwright JSON report — E1 Flaky Governance
Reads test-results/results.json and outputs stability metrics.
"""
import json
import sys
import os
from datetime import datetime
from typing import Any

def parse_results(json_path: str) -> dict[str, Any]:
    """Parse Playwright JSON report and extract stability metrics."""
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    stats = data.get('stats', {})
    tests = data.get('tests', [])

    total = stats.get('total', 0)
    passed = stats.get('passed', 0)
    failed = stats.get('failed', 0)
    skipped = stats.get('skipped', 0)
    flaky = 0

    # Identify flaky tests: tests that ran more than once (retries)
    test_results: dict[str, list] = {}
    for t in tests:
        title = ' '.join(t.get('title', []))
        status = t.get('status', 'unknown')
        if title not in test_results:
            test_results[title] = []
        test_results[title].append(status)

    # Flaky = same test passed on retry after failing
    for title, statuses in test_results.items():
        if 'failed' in statuses and 'passed' in statuses:
            flaky += 1

    pass_rate = (passed / total * 100) if total > 0 else 0.0

    return {
        'total': total,
        'passed': passed,
        'failed': failed,
        'skipped': skipped,
        'flaky': flaky,
        'pass_rate': round(pass_rate, 1),
        'report_time': stats.get('startTime', ''),
        'duration': stats.get('duration', 0),
    }


def append_to_log(metrics: dict[str, Any], log_path: str) -> None:
    """Append metrics to the daily stability log."""
    os.makedirs(os.path.dirname(log_path) or '.', exist_ok=True)

    date_str = datetime.now().strftime('%Y-%m-%d')
    time_str = datetime.now().strftime('%H:%M:%S')

    # CSV-style row
    row = f"| {date_str} {time_str} | {metrics['pass_rate']}% | {metrics['total']} | {metrics['passed']} | {metrics['failed']} | {metrics['flaky']} |"

    # Check if header exists
    header = "| Date | PassRate | Total | Passed | Failed | Flaky |"
    marker = "## Daily Stability Log"

    if not os.path.exists(log_path):
        # Create new log with header
        content = f"""# Daily Stability Log

Generated by: scripts/test-stability-report.sh

## Format

- **PassRate**: passed/total × 100%
- **Flaky**: tests that passed after retry (indicates timing sensitivity)
- Target: PassRate >= 95%, Flaky <= 1

{marker}

{header}
|---|---|---|---|---|---|
{row}
"""
    else:
        with open(log_path, 'r', encoding='utf-8') as f:
            content = f.read()

        if marker in content:
            # Append row after the marker
            content = content.replace(
                f"{marker}\n",
                f"{marker}\n{row}\n"
            )
        else:
            content += f"\n{row}\n"

    with open(log_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Log updated: {log_path}")


def main():
    if len(sys.argv) < 2:
        print("Usage: parse-playwright-report.py <results.json>")
        sys.exit(1)

    json_path = sys.argv[1]

    if not os.path.exists(json_path):
        print(f"Error: File not found: {json_path}")
        sys.exit(1)

    try:
        metrics = parse_results(json_path)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in {json_path}: {e}")
        sys.exit(1)

    # Print summary
    print(f"\n{'='*40}")
    print(f"  E2E Stability Report — {datetime.now().strftime('%Y-%m-%d')}")
    print(f"{'='*40}")
    print(f"  Total:   {metrics['total']}")
    print(f"  Passed:  {metrics['passed']}  ✅")
    print(f"  Failed:  {metrics['failed']}  ❌")
    print(f"  Skipped: {metrics['skipped']}")
    print(f"  Flaky:   {metrics['flaky']}  ⚠️")
    print(f"  PassRate: {metrics['pass_rate']}%")
    print(f"{'='*40}")

    # Append to log
    log_path = os.path.join(os.path.dirname(json_path) or '.', '..', 'docs', 'daily-stability.md')
    try:
        append_to_log(metrics, log_path)
    except Exception as e:
        print(f"Warning: Could not update log: {e}")

    # Exit with failure if pass rate is below threshold
    if metrics['pass_rate'] < 95.0:
        print(f"\n⚠️  FAIL: Pass rate {metrics['pass_rate']}% < 95%")
        sys.exit(1)
    else:
        print(f"\n✅ PASS: Pass rate {metrics['pass_rate']}% >= 95%")
        sys.exit(0)


if __name__ == '__main__':
    main()
