/**
 * E1-U4: Generate tool index documentation
 *
 * Reads tool definitions from packages/mcp-server/src/tools/list.ts
 * and generates docs/mcp-tools/INDEX.md with a markdown table.
 *
 * Usage: node scripts/generate-tool-index.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const OUTPUT_DIR = path.join(ROOT, 'docs/mcp-tools');
const OUTPUT_PATH = path.join(OUTPUT_DIR, 'INDEX.md');

// Use ts-node to compile & run the TypeScript source directly,
// importing listTools() from the actual mcp-server module.
const MCP_SERVER_SRC = path.join(ROOT, 'packages/mcp-server/src');
const TOOLS_PATH = path.join(MCP_SERVER_SRC, 'tools/list.ts');

async function main() {
  // Dynamically import listTools by evaluating the TypeScript source.
  // We use a subprocess with tsx to handle TypeScript compilation.
  const { execSync } = await import('node:child_process');

  // Run a quick tsx script that imports listTools and outputs JSON
  const script = `
import { listTools } from '${TOOLS_PATH.replace(/\\/g, '/')}'.js';
const tools = listTools();
process.stdout.write(JSON.stringify(tools.map(t => ({
  name: t.name,
  description: t.description,
  inputSchema: t.inputSchema,
})));
`.trim();

  let json: Array<{ name: string; description: string; inputSchema: object }>;
  try {
    const out = execSync(`node --import tsx/esm <<'EOF'\n${script}\nEOF`, {
      cwd: ROOT,
      encoding: 'utf-8',
    });
    json = JSON.parse(out);
  } catch (e) {
    // Fallback: parse source directly
    console.warn('[generate-tool-index] tsx eval failed, using regex fallback');
    const source = fs.readFileSync(TOOLS_PATH, 'utf-8');
    const nameMatches = [...source.matchAll(/name:\s*['"]([^'"]+)['"]/g)];
    const descMatches = [...source.matchAll(/description:\s*['"]([^'"]+)['"]/g)];
    json = nameMatches.map((m, i) => ({
      name: m[1],
      description: descMatches[i]?.[1] ?? '',
      inputSchema: {},
    }));
  }

  const lines: string[] = [
    '# VibeX MCP Tools Index',
    '',
    `> Auto-generated by \`scripts/generate-tool-index.ts\` at ${new Date().toISOString()}.`,
    '',
    `Total tools: **${json.length}**`,
    '',
    '## Tool List',
    '',
    '| # | Tool Name | Description | Input Schema |',
    '|---|-----------|-------------|--------------|',
  ];

  json.forEach((tool, i) => {
    const schemaStr = JSON.stringify(tool.inputSchema).substring(0, 120);
    lines.push(
      `| ${i + 1} | \`${tool.name}\` | ${tool.description} | \`${schemaStr}\` |`
    );
  });

  lines.push('');
  lines.push('---');
  lines.push('*This file is auto-generated. Do not edit manually.*');

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, lines.join('\n') + '\n', 'utf-8');
  console.log(`[generate-tool-index] Wrote ${json.length} tools to ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error('[generate-tool-index] Error:', err);
  process.exit(1);
});