/**
 * E1-U4: Generate tool index documentation
 *
 * Reads tool definitions from packages/mcp-server/src/tools/list.ts
 * and generates docs/mcp-tools/INDEX.md with a markdown table.
 *
 * Usage: node scripts/generate-tool-index.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const TOOLS_PATH = path.join(ROOT, 'packages/mcp-server/src/tools/list.ts');
const OUTPUT_DIR = path.join(ROOT, 'docs/mcp-tools');
const OUTPUT_PATH = path.join(OUTPUT_DIR, 'INDEX.md');

interface ParsedTool {
  name: string;
  description: string;
  inputSchemaRaw: string;
}

/**
 * Parse each tool block from the `return [...]` in listTools().
 * Uses a state machine to find:
 *   name: '...'  ->  description: '...'  ->  inputSchema: { ... }
 * Handles multi-line and nested-brace inputSchema objects.
 */
function parseTools(source: string): ParsedTool[] {
  const returnMatch = source.match(/return\s*\[\s*([\s\S]*?)\s*\]\s*;/);
  if (!returnMatch) return [];

  const block = returnMatch[1];
  const tools: ParsedTool[] = [];
  let idx = 0;

  while (idx < block.length) {
    const namePos = block.indexOf("name: '", idx);
    if (namePos === -1) break;

    // Extract name
    const nameEnd = block.indexOf("'", namePos + 7);
    const name = block.substring(namePos + 7, nameEnd);
    idx = nameEnd + 1;

    // Extract description
    const descPos = block.indexOf("description: '", idx);
    const descEnd = block.indexOf("'", descPos + 14);
    const description = block.substring(descPos + 14, descEnd);
    idx = descEnd + 1;

    // Extract inputSchema: { ...balanced... }
    const schemaPos = block.indexOf('inputSchema:', idx);
    const braceStart = block.indexOf('{', schemaPos + 13);
    let depth = 1, schemaEnd = braceStart + 1;
    while (depth > 0 && schemaEnd < block.length) {
      if (block[schemaEnd] === '{') depth++;
      else if (block[schemaEnd] === '}') depth--;
      schemaEnd++;
    }
    const inputSchemaRaw = block.substring(braceStart, schemaEnd).trim();
    idx = schemaEnd;

    tools.push({ name, description, inputSchemaRaw });
  }

  return tools;
}

function main() {
  const source = fs.readFileSync(TOOLS_PATH, 'utf-8');
  const tools = parseTools(source);

  if (tools.length === 0) {
    console.error('[generate-tool-index] No tools found in list.ts');
    process.exit(1);
  }

  const lines: string[] = [
    '# VibeX MCP Tools Index',
    '',
    `> Auto-generated by \`scripts/generate-tool-index.ts\` at ${new Date().toISOString()}.`,
    '',
    `Total tools: **${tools.length}**`,
    '',
    '## Tool List',
    '',
    '| # | Tool Name | Description |',
    '|---|-----------|-------------|',
  ];

  tools.forEach((tool, i) => {
    lines.push(`| ${i + 1} | \`${tool.name}\` | ${tool.description} |`);
  });

  lines.push('');
  lines.push('## Input Schemas', '');
  lines.push('| # | Tool Name | Input Schema |');
  lines.push('|---|-----------|--------------|');

  tools.forEach((tool, i) => {
    // Truncate long schema for readability in table
    const schemaPreview = tool.inputSchemaRaw.length > 100
      ? tool.inputSchemaRaw.substring(0, 97) + '...'
      : tool.inputSchemaRaw;
    lines.push(`| ${i + 1} | \`${tool.name}\` | \`${schemaPreview}\` |`);
  });

  lines.push('');
  lines.push('---');
  lines.push('*This file is auto-generated. Do not edit manually.*');

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, lines.join('\n') + '\n', 'utf-8');
  console.log(`[generate-tool-index] Wrote ${tools.length} tools to ${OUTPUT_PATH}`);
}

main();