/**
 * 类型生成脚本
 * 从 OpenAPI 规范自动生成 TypeScript 类型
 * 
 * 使用方式:
 *   pnpm generate:types
 * 
 * 环境变量:
 *   OPENAPI_URL - OpenAPI 规范 URL (默认: http://localhost:3000/api/openapi.json)
 */
// @ts-nocheck


import { execSync } from 'child_process';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';

const OPENAPI_URL = process.env.OPENAPI_URL || 'http://localhost:3000/api/openapi.json';
const OUTPUT_FILE = join(process.cwd(), 'src/types/api-generated.ts');

async function generateTypes() {
  console.log('🔧 Generating TypeScript types from OpenAPI...');
  console.log(`   URL: ${OPENAPI_URL}`);
  console.log(`   Output: ${OUTPUT_FILE}`);

  // 检查 OpenAPI 端点是否可用
  try {
    execSync(`curl -sf "${OPENAPI_URL}" > /dev/null`, { stdio: 'pipe' });
  } catch {
    console.warn('⚠️  OpenAPI endpoint not available. Skipping type generation.');
    console.log('   To generate types, run the dev server: pnpm dev');
    
    // 创建空的类型文件作为占位符
    const placeholder = `/**
 * Auto-generated TypeScript types from OpenAPI
 * DO NOT EDIT - regenerate with pnpm generate:types
 * 
 * Note: OpenAPI endpoint not available. Run 'pnpm dev' and retry.
 * 
 * Generated at: ${new Date().toISOString()}
 */

export interface paths {}
export interface components {}
export type operations = {};
`;
    
    // 确保目录存在
    const { mkdirSync } = await import('fs');
    mkdirSync(join(process.cwd(), 'src/types'), { recursive: true });
    writeFileSync(OUTPUT_FILE, placeholder);
    console.log('✅ Created placeholder types file.');
    return;
  }

  try {
    // 从 OpenAPI 规范生成类型
    execSync(`npx openapi-typescript "${OPENAPI_URL}" -o "${OUTPUT_FILE}"`, {
      stdio: 'inherit'
    });

    // 添加文件头注释
    const content = readFileSync(OUTPUT_FILE, 'utf-8');
    const header = `/**
 * Auto-generated by openapi-typescript
 * DO NOT EDIT - regenerate with pnpm generate:types
 * 
 * Generated at: ${new Date().toISOString()}
 */

`;
    writeFileSync(OUTPUT_FILE, header + content);

    console.log('✅ Types generated successfully!');
    console.log(`   Output: ${OUTPUT_FILE}`);
  } catch (error) {
    console.error('❌ Failed to generate types:', error);
    process.exit(1);
  }
}

generateTypes().catch(console.error);
