/**
 * Bounded Contexts Filter Module
 *
 * Validates and filters bounded contexts generated by LLM.
 * Ensures quality: name length, forbidden patterns, core ratio bounds.
 */

import type { BoundedContext } from './prompts/bounded-contexts';

export interface FilterOptions {
  /** Minimum character length for context name */
  minNameLength?: number;
  /** Maximum character length for context name */
  maxNameLength?: number;
  /** Names that should be filtered out (e.g. generic words) */
  forbiddenNames?: string[];
  /** Minimum ratio of core contexts (0-1) */
  minCoreRatio?: number;
  /** Maximum ratio of core contexts (0-1) */
  maxCoreRatio?: number;
}

const DEFAULT_OPTIONS: Required<FilterOptions> = {
  minNameLength: 2,
  maxNameLength: 10,
  forbiddenNames: ['管理', '系统', '模块', '功能', '平台'],
  minCoreRatio: 0.4,
  maxCoreRatio: 0.7,
};

/**
 * Check if a bounded context name should be filtered out.
 */
export function isNameFiltered(name: string, options?: FilterOptions): boolean {
  const opts = { ...DEFAULT_OPTIONS, ...options };

  // Check name length
  if (name.length < opts.minNameLength || name.length > opts.maxNameLength) {
    return true;
  }

  // Check forbidden names
  if (opts.forbiddenNames.some(n => name.includes(n))) {
    return true;
  }

  return false;
}

/**
 * Filter out invalid bounded contexts from an LLM response.
 */
export function filterInvalidContexts(
  contexts: BoundedContext[],
  options?: FilterOptions
): BoundedContext[] {
  return contexts.filter(ctx => !isNameFiltered(ctx.name, options));
}

/**
 * Validate that the ratio of core contexts is within acceptable bounds.
 */
export function validateCoreRatio(
  contexts: BoundedContext[],
  options?: FilterOptions
): { valid: boolean; ratio: number; message?: string } {
  const opts = { ...DEFAULT_OPTIONS, ...options };

  if (contexts.length === 0) {
    return { valid: true, ratio: 0 };
  }

  const coreCount = contexts.filter(c => c.type === 'core').length;
  const ratio = coreCount / contexts.length;
  const valid = ratio >= opts.minCoreRatio && ratio <= opts.maxCoreRatio;

  return {
    valid,
    ratio,
    message: valid ? undefined : `core 占比 ${(ratio * 100).toFixed(1)}% 不在 ${(opts.minCoreRatio * 100)}%-${(opts.maxCoreRatio * 100)}% 范围内`,
  };
}
