/**
 * Code Generator — E10 Sprint 12
 *
 * Generates TypeScript type definitions, TSX component skeletons, and CSS Modules
 * from canvas Flow + CanvasNode data.
 *
 * @module lib/codeGenerator
 */

import JSZip from 'jszip';

// =============================================================================
// Types
// =============================================================================

/** A canvas flow with its associated nodes */
export interface CanvasFlow {
  id?: string;
  name?: string;
  nodes?: CanvasNode[];
}

/** A canvas node (context, flow, or component) */
export interface CanvasNode {
  id: string;
  name?: string;
  type?: string;
  description?: string;
  position?: { x: number; y: number };
  [key: string]: unknown;
}

/** Node type enumeration for canvas nodes */
export type CanvasNodeType =
  | 'bounded-context'
  | 'flow'
  | 'component'
  | 'user-task'
  | 'system-task'
  | 'event'
  | 'gateway'
  | 'page'
  | 'form'
  | 'list'
  | 'detail'
  | 'modal';

/** A chapter/section in a flow */
export interface Chapter {
  id: string;
  name: string;
  steps?: Array<{
    id: string;
    name: string;
    type: string;
  }>;
}

/** Framework target for code generation */
export type TargetFramework = 'react' | 'vue' | 'solid';

/** Generated file bundle */
export interface GeneratedFiles {
  types: string;      // TypeScript type definitions (.d.ts)
  component: string;  // Component skeleton (.tsx)
  css: string;       // CSS Module (.module.css)
  scss: string;      // SCSS variables (.scss)
  js: string;        // JS/TS constants (.ts)
  index: string;     // Entry point (.ts)
}

// =============================================================================
// Constants
// =============================================================================

const MAX_NODES_LIMIT = 200;

/** Design system CSS variable prefixes used in output */
const DESIGN_CSS_VARS = [
  '--color-primary',
  '--color-secondary',
  '--color-background',
  '--color-surface',
  '--color-border',
  '--color-text-primary',
  '--color-text-secondary',
  '--color-error',
  '--color-success',
  '--color-warning',
  '--spacing-1',
  '--spacing-2',
  '--spacing-3',
  '--spacing-4',
  '--spacing-5',
  '--spacing-6',
  '--spacing-8',
  '--spacing-10',
  '--spacing-12',
  '--radius-sm',
  '--radius-md',
  '--radius-lg',
  '--radius-xl',
  '--font-sans',
  '--font-mono',
  '--text-xs',
  '--text-sm',
  '--text-base',
  '--text-lg',
  '--text-xl',
] as const;

// =============================================================================
// Type Definition Generator
// =============================================================================

/**
 * Generate TypeScript type definitions from canvas nodes.
 * Outputs interfaces for Flow, CanvasNode, Chapter, and all node types.
 */
function generateTypeDefinitions(flow: CanvasFlow): string {
  const flowName = sanitizeName(flow.name ?? 'Flow');
  const componentName = `${flowName}Component`;
  const typesName = `${flowName}Types`;

  const nodes = flow.nodes ?? [];
  const contextNodes = nodes.filter((n) => n.type === 'bounded-context' || n.type === 'context');
  const flowNodes = nodes.filter((n) => n.type === 'flow' || n.type === 'user-task' || n.type === 'system-task');
  const componentNodes = nodes.filter((n) => n.type === 'component' || n.type === 'page' || n.type === 'form' || n.type === 'list');

  const lines: string[] = [
    `/**`,
    ` * ${typesName}`,
    ` * Auto-generated by VibeX Code Generator`,
    ` * Canvas Flow: ${flow.name ?? 'Unnamed'}`,
    ` */`,
    ``,
    `// ============================================================================`,
    `// Canvas Core Types`,
    `// ============================================================================`,
    ``,
    `export interface CanvasNode {`,
    `  id: string;`,
    `  name?: string;`,
    `  type?: string;`,
    `  description?: string;`,
    `  position?: { x: number; y: number };`,
    `  [key: string]: unknown;`,
    `}`,
    ``,
    `export interface Chapter {`,
    `  id: string;`,
    `  name: string;`,
    `  steps?: Array<{ id: string; name: string; type: string }>;`,
    `}`,
    ``,
    `export interface CanvasFlow {`,
    `  id?: string;`,
    `  name?: string;`,
    `  nodes?: CanvasNode[];`,
    `}`,
    ``,
    `// ============================================================================`,
    `// Flow-Specific Types — ${flowName}`,
    `// ============================================================================`,
    ``,
    `export type ${flowName}NodeType =`,
    contextNodes.length > 0 ? `  | 'bounded-context'` : '',
    flowNodes.length > 0 ? `  | 'flow' | 'user-task' | 'system-task'` : '',
    componentNodes.length > 0 ? `  | 'component' | 'page' | 'form' | 'list'` : '',
    `  | string;`,
    ``,
  ];

  // Generate per-node-type interfaces
  if (contextNodes.length > 0) {
    lines.push(`export interface ${flowName}ContextNode extends CanvasNode {`);
    lines.push(`  type: 'bounded-context';`);
    lines.push(`  children?: string[]; // IDs of child nodes`);
    lines.push(`}`);
    lines.push(``);
  }

  if (flowNodes.length > 0) {
    lines.push(`export interface ${flowName}FlowNode extends CanvasNode {`);
    lines.push(`  type: 'flow';`);
    lines.push(`  actor?: string;`);
    lines.push(`  triggers?: string[];`);
    lines.push(`  steps?: Array<{ id: string; name: string; type: string }>;`);
    lines.push(`}`);
    lines.push(``);
  }

  if (componentNodes.length > 0) {
    lines.push(`export interface ${flowName}ComponentNode extends CanvasNode {`);
    lines.push(`  type: 'component';`);
    lines.push(`  props?: Record<string, unknown>;`);
    lines.push(`  api?: { method: 'GET' | 'POST'; path: string };`);
    lines.push(`}`);
    lines.push(``);
  }

  // Node map type
  lines.push(`export type ${flowName}Node =`);
  if (contextNodes.length > 0) lines.push(`  | ${flowName}ContextNode`);
  if (flowNodes.length > 0) lines.push(`  | ${flowName}FlowNode`);
  if (componentNodes.length > 0) lines.push(`  | ${flowName}ComponentNode`);
  lines.push(`  | CanvasNode;`);
  lines.push(``);

  lines.push(`// ============================================================================`);
  lines.push(`// Component Props`);
  lines.push(`// ============================================================================`);
  lines.push(``);
  lines.push(`export interface ${componentName}Props {`);
  lines.push(`  /** Optional className override */`);
  lines.push(`  className?: string;`);
  lines.push(`  /** Initial data for the component */`);
  lines.push(`  initialData?: Partial<${flowName}Node>;`);
  lines.push(`  /** Callback when data changes */`);
  lines.push(`  onChange?: (data: Partial<${flowName}Node>) => void;`);
  lines.push(`}`);

  return lines.filter(Boolean).join('\n');
}

// =============================================================================
// TSX Component Skeleton Generator
// =============================================================================

/**
 * Generate a TSX component skeleton.
 * Uses CSS variables for all design tokens — no hardcoded values.
 */
function generateTSXSkeleton(flow: CanvasFlow, framework: TargetFramework): string {
  const flowName = sanitizeName(flow.name ?? 'Flow');
  const componentName = `${flowName}Component`;
  const nodes = flow.nodes ?? [];

  const imports: string[] = [];
  const jsxContent: string[] = [];

  if (framework === 'react') {
    imports.push(`import React from 'react';`);
    imports.push(`import type { ${componentName}Props } from './${flowName}.types';`);
    imports.push(`import styles from './${flowName}.module.css';`);
    imports.push(``);
    imports.push(`/**`);
    imports.push(` * ${componentName} — auto-generated TSX skeleton`);
    imports.push(` *`);
    imports.push(` * @generated by VibeX Code Generator`);
    imports.push(` * @TODO Implement component logic based on canvas design`);
    imports.push(` */`);
    imports.push(``);
    imports.push(`export function ${componentName}({ className, initialData, onChange }: ${componentName}Props) {`);

    // TODO comments for each node type
    const contextNodes = nodes.filter((n) => n.type === 'bounded-context');
    const flowNodes = nodes.filter((n) => n.type === 'flow' || n.type === 'user-task');
    const componentNodes = nodes.filter((n) => n.type === 'component');

    if (contextNodes.length > 0) {
      jsxContent.push(`  // TODO: Implement bounded context sections (${contextNodes.length} contexts)`);
      for (const node of contextNodes.slice(0, 3)) {
        jsxContent.push(`  //   - ${node.name ?? node.id} (${node.type})`);
      }
    }

    if (flowNodes.length > 0) {
      jsxContent.push(`  // TODO: Implement flow steps (${flowNodes.length} flows)`);
      for (const node of flowNodes.slice(0, 3)) {
        jsxContent.push(`  //   - ${node.name ?? node.id} (${node.type})`);
      }
    }

    if (componentNodes.length > 0) {
      jsxContent.push(`  // TODO: Implement component rendering (${componentNodes.length} components)`);
      for (const node of componentNodes.slice(0, 3)) {
        jsxContent.push(`  //   - ${node.name ?? node.id} (${node.type})`);
      }
    }

    jsxContent.push(``);
    jsxContent.push(`  return (`);
    jsxContent.push(`    <div className={\`\${styles.container}\${className ? \` \${className}\` : ''}\`}>`);
    jsxContent.push(`      {/* @TODO: Replace with actual component implementation */}`);
    jsxContent.push(`      <div className={styles.header}>`);
    jsxContent.push(`        <h2 className={styles.title}>{initialData?.name ?? '${flowName}'}</h2>`);
    jsxContent.push(`      </div>`);
    jsxContent.push(`      <div className={styles.content}>`);
    jsxContent.push(`        {/* @TODO: Add flow and component rendering */}`);
    jsxContent.push(`      </div>`);
    jsxContent.push(`    </div>`);
    jsxContent.push(`  );`);
    jsxContent.push(`}`);

  } else if (framework === 'vue') {
    imports.push(`<script setup lang="ts">`);
    imports.push(`import type { ${componentName}Props } from './${flowName}.types';`);
    imports.push(`defineProps<${componentName}Props>();`);
    imports.push(`</script>`);
    imports.push(``);
    imports.push(`<template>`);
    imports.push(`  <div class="${flowName.toLowerCase()}">`);
    imports.push(`    <!-- @TODO: Implement Vue component -->`);
    imports.push(`  </div>`);
    imports.push(`</template>`);

  } else {
    imports.push(`// @TODO: Implement ${framework} component`);
    imports.push(`export function ${componentName}() { return null; }`);
  }

  return [...imports, '', ...jsxContent].join('\n');
}

// =============================================================================
// CSS Module Generator
// =============================================================================

/**
 * Generate a CSS Module using design system CSS variables.
 * All values use CSS variables — no hardcoded colors or spacing.
 */
function generateCSSModule(flow: CanvasFlow): string {
  const flowName = sanitizeName(flow.name ?? 'Flow');
  const nodes = flow.nodes ?? [];

  const lines: string[] = [
    `/**`,
    ` * ${flowName}.module.css — auto-generated CSS Module`,
    ` *`,
    ` * Design tokens (CSS variables) used throughout:`,
    ` * - Color: var(--color-primary), var(--color-text-primary), etc.`,
    ` * - Spacing: var(--spacing-1) through var(--spacing-12) (4px grid)`,
    ` * - Typography: var(--text-sm), var(--font-sans), etc.`,
    ` * - Border: var(--radius-sm) through var(--radius-xl)`,
    ` *`,
    ` * @generated by VibeX Code Generator`,
    ` * @TODO Implement styles based on canvas design`,
    ` */`,
    ``,
    `/* ============================================================================`,
    ` * Container`,
    ` * ============================================================================ */`,
    ``,
    `.container {`,
    `  display: flex;`,
    `  flex-direction: column;`,
    `  gap: var(--spacing-4, 16px);`,
    `  padding: var(--spacing-6, 24px);`,
    `  background: var(--color-surface, var(--color-bg-primary, #fff));`,
    `  border-radius: var(--radius-lg, 12px);`,
    `  border: 1px solid var(--color-border, #e5e7eb);`,
    `}`,
    ``,
    `/* ============================================================================`,
    ` * Header`,
    ` * ============================================================================ */`,
    ``,
    `.header {`,
    `  display: flex;`,
    `  align-items: center;`,
    `  justify-content: space-between;`,
    `  gap: var(--spacing-4, 16px);`,
    `  padding-bottom: var(--spacing-4, 16px);`,
    `  border-bottom: 1px solid var(--color-border, #e5e7eb);`,
    `}`,
    ``,
    `.title {`,
    `  margin: 0;`,
    `  font-size: var(--text-lg, 18px);`,
    `  font-weight: var(--font-semibold, 600);`,
    `  font-family: var(--font-sans, sans-serif);`,
    `  color: var(--color-text-primary, #111827);`,
    `  line-height: 1.4;`,
    `}`,
    ``,
    `/* ============================================================================`,
    ` * Content Area`,
    ` * ============================================================================ */`,
    ``,
    `.content {`,
    `  display: flex;`,
    `  flex-direction: column;`,
    `  gap: var(--spacing-3, 12px);`,
    `}`,
    ``,
    `/* ============================================================================`,
    ` * Context/Section Styles (${nodes.filter(n => n.type === 'bounded-context').length} contexts)`,
    ` * ============================================================================ */`,
    ``,
    `.context {`,
    `  padding: var(--spacing-4, 16px);`,
    `  background: var(--color-surface, var(--color-bg-secondary, #f9fafb));`,
    `  border-radius: var(--radius-md, 8px);`,
    `  border: 1px solid var(--color-border, #e5e7eb);`,
    `}`,
    ``,
    `.contextName {`,
    `  margin: 0 0 var(--spacing-2, 8px) 0;`,
    `  font-size: var(--text-base, 16px);`,
    `  font-weight: var(--font-semibold, 600);`,
    `  color: var(--color-text-primary, #111827);`,
    `}`,
    ``,
    `/* ============================================================================`,
    ` * Flow/Step Styles (${nodes.filter(n => n.type?.includes('task')).length} tasks)`,
    ` * ============================================================================ */`,
    ``,
    `.step {`,
    `  display: flex;`,
    `  align-items: flex-start;`,
    `  gap: var(--spacing-3, 12px);`,
    `  padding: var(--spacing-3, 12px);`,
    `  border-radius: var(--radius-md, 8px);`,
    `  transition: background 0.2s ease;`,
    `}`,
    ``,
    `.step:hover {`,
    `  background: var(--color-surface, var(--color-bg-secondary, #f9fafb));`,
    `}`,
    ``,
    `/* ============================================================================`,
    ` * Component Styles (${nodes.filter(n => n.type === 'component').length} components)`,
    ` * ============================================================================ */`,
    ``,
    `.component {`,
    `  padding: var(--spacing-4, 16px);`,
    `  background: var(--color-surface, #fff);`,
    `  border-radius: var(--radius-md, 8px);`,
    `  border: 1px solid var(--color-border, #e5e7eb);`,
    `  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);`,
    `}`,
    ``,
    `/* ============================================================================`,
    ` * Responsive`,
    ` * ============================================================================ */`,
    ``,
    `@media (max-width: 640px) {`,
    `  .container {`,
    `    padding: var(--spacing-4, 16px);`,
    `  }`,
    `  .title {`,
    `    font-size: var(--text-base, 16px);`,
    `  }`,
    `}`,
  ];

  return lines.join('\n');
}

// =============================================================================
// Index File Generator
// =============================================================================

/**
 * Generate the index.ts entry point.
 */
function generateIndexFile(flow: CanvasFlow, framework: TargetFramework): string {
  const flowName = sanitizeName(flow.name ?? 'Flow');
  const componentName = `${flowName}Component`;

  if (framework === 'react') {
    return [
      `/**`,
      ` * ${flowName} — auto-generated index`,
      ` * @generated by VibeX Code Generator`,
      ` */`,
      ``,
      `export type { ${flowName}Node, ${flowName}FlowNode, ${flowName}ContextNode, ${flowName}ComponentNode } from './${flowName}.types';`,
      `export type { ${componentName}Props } from './${flowName}.types';`,
      `export { ${componentName} } from './${flowName}.tsx';`,
    ].join('\n');
  }

  return `export { ${componentName} } from './${flowName}.${framework === 'vue' ? 'vue' : 'tsx'}';`;
}

// =============================================================================
// SCSS Variables Generator — E1 Design-to-Code Pipeline
// =============================================================================

/**
 * Generate SCSS variables from a canvas flow.
 * Maps CSS custom properties to SCSS $ variables.
 */
function generateSCSS(flow: CanvasFlow): string {
  const flowName = sanitizeName(flow.name ?? 'Flow');
  const nodes = flow.nodes ?? [];

  const lines: string[] = [
    `// ${flowName}.scss — VibeX Design Tokens (SCSS)`,
    `// Generated: ${new Date().toISOString()}`,
    ``,
  ];

  for (const cssVar of DESIGN_CSS_VARS) {
    const scssVarName = cssVar.replace('--', '').replace(/-/g, '_');
    lines.push(`$${scssVarName}: var(${cssVar});`);
  }

  // Node-specific variables
  for (const node of nodes.slice(0, 20)) {
    const nodeName = sanitizeName(node.name ?? node.id).replace(/([A-Z])/g, '-$1').toLowerCase();
    lines.push(`$${nodeName}: var(--spacing-4);`);
  }

  return lines.join('\n');
}

// =============================================================================
// JS/TS Constants Generator — E1 Design-to-Code Pipeline
// =============================================================================

/**
 * Generate JS/TS constants from a canvas flow.
 * Exports design tokens as typed constants.
 */
function generateJSConstants(flow: CanvasFlow): string {
  const flowName = sanitizeName(flow.name ?? 'Flow');
  const nodes = flow.nodes ?? [];

  const lines: string[] = [
    `/**`,
    ` * ${flowName}.constants.ts — VibeX Design Token Constants`,
    ` * Generated: ${new Date().toISOString()}`,
    ` */`,
    ``,
    `/** Design token values as CSS variable references */`,
    `export const DESIGN_TOKENS = {`,
  ];

  for (const cssVar of DESIGN_CSS_VARS) {
    const key = cssVar.replace('--', '').replace(/-/g, '_').toUpperCase();
    lines.push(`  ${key}: '${cssVar}',`);
  }

  lines.push(`} as const;`, ``);

  // Node metadata
  if (nodes.length > 0) {
    lines.push(`/** Node metadata from canvas */`);
    lines.push(`export const CANVAS_NODES = [`);
    for (const node of nodes.slice(0, 20)) {
      lines.push(`  { id: '${node.id}', name: '${node.name ?? ''}', type: '${node.type ?? ''}' },`);
    }
    lines.push(`] as const;`);
  }

  return lines.join('\n');
}

// =============================================================================
// Utilities
// =============================================================================

/**
 * Sanitize a string into a valid PascalCase TypeScript identifier.
 */
function sanitizeName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\u4e00-\u9fa5]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

// =============================================================================
// Public API
// =============================================================================

export interface GenerateResult {
  /** Generated files */
  files: GeneratedFiles;
  /** Total nodes in flow */
  nodeCount: number;
  /** Whether node limit was exceeded */
  limitExceeded: boolean;
  /** Limit that was exceeded */
  limit: number;
  /** Sanitized component name */
  componentName: string;
}

/**
 * Generate code files from a canvas flow.
 *
 * @param flow - The canvas flow with nodes
 * @param framework - Target framework (default: react)
 * @returns Generated files and metadata
 */
export function generateComponentCode(
  flow: CanvasFlow,
  framework: TargetFramework = 'react'
): GenerateResult {
  const nodes = flow.nodes ?? [];
  const limitExceeded = nodes.length > MAX_NODES_LIMIT;
  const flowName = sanitizeName(flow.name ?? 'Flow');

  return {
    files: {
      types: generateTypeDefinitions(flow),
      component: generateTSXSkeleton(flow, framework),
      css: generateCSSModule(flow),
      scss: generateSCSS(flow),
      js: generateJSConstants(flow),
      index: generateIndexFile(flow, framework),
    },
    nodeCount: nodes.length,
    limitExceeded,
    limit: MAX_NODES_LIMIT,
    componentName: `${flowName}Component`,
  };
}

/**
 * Package generated files as a ZIP blob.
 *
 * @param result - Result from generateComponentCode
 * @param flowName - Optional override for the file prefix (default: flow name)
 * @returns ZIP blob ready for download
 */
export async function packageAsZip(
  result: GenerateResult,
  flowName?: string
): Promise<Blob> {
  const prefix = sanitizeName(flowName ?? result.componentName.replace(/Component$/, ''));
  const zip = new JSZip();

  // Add all generated files
  zip.file(`${prefix}.types.ts`, result.files.types);
  zip.file(`${prefix}.tsx`, result.files.component);
  zip.file(`${prefix}.module.css`, result.files.css);
  zip.file(`${prefix}.scss`, result.files.scss);
  zip.file(`${prefix}.constants.ts`, result.files.js);
  zip.file(`index.ts`, result.files.index);

  // Add README
  zip.file('README.md', [
    `# ${prefix}`,
    '',
    'Auto-generated by VibeX Code Generator',
    '',
    '## Files',
    '',
    `- \`${prefix}.types.ts\` — TypeScript type definitions`,
    `- \`${prefix}.tsx\` — Component skeleton`,
    `- \`${prefix}.module.css\` — CSS Module (design system variables)`,
    `- \`${prefix}.scss\` — SCSS variables (E1)`,
    `- \`${prefix}.constants.ts\` — JS/TS constants (E1)`,
    `- \`index.ts\` — Entry point`,
    '',
    '## Usage',
    '',
    '```tsx',
    `import { ${result.componentName} } from './${prefix}';`,
    '',
    `<${result.componentName} initialData={{}} />`,
    '```',
    '',
    `Generated from ${result.nodeCount} canvas nodes.`,
    result.limitExceeded
      ? `\n⚠️ Warning: Node count (${result.nodeCount}) exceeded limit (${result.limit}).`
      : '',
  ].join('\n'));

  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
}

/** Export constants for external use */
export { MAX_NODES_LIMIT, DESIGN_CSS_VARS };
